### ISSUE TITLE
[BUG] Downloading

### ISSUE THREAD

**Issue by YuckyFox** [BlafKing/sd-civitai-browser-plus#24]
**Describe the bug**
All models, loras etc. not downloading

**To Reproduce**
1. Download any model
2. See nothing happening

**Expected behavior**
Model downloading? I think old download method worked fine

**Screenshots**
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/110828409/7a877be0-84ef-4251-a1cc-ec0e3bbc5063)

**Additional context**
* Extension version: 1.9.3
* OS: (Windows)
* SD version: A1111, Latest version
* Python: 3.10.8

**Comment by BlafKing** [comment]
Unfortunate to see you're experiencing issues I know what the cause is so I've posted a fix right now, thanks for letting me know!
Please let me know if the issue has been fixed for you, if so I'll close this thread 👍🏻

**Comment by YuckyFox** [comment]
Nope, it's not, here's a screenshot
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/110828409/4ffe51bc-8eef-4613-a108-7c9fed407bbb)

**Comment by BlafKing** [comment]
Made a mistake in the fix my bad, please try one more time by downloading the latest version just published another hotfix.
If you still experience issues after properly updating can you send me a screenshot of the civitai_download.py file inside the extension?
Inside that file please make a screenshot of line 36 and 37

**Comment by YuckyFox** [comment]
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/110828409/1b12eef6-ed4e-4659-b494-d3bc4cebcbcd)
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/110828409/bd297000-b4ac-4e98-bd8e-2fc726c3b3b0)
I just checked download with VPN and it actually works, i guess this is my internet bad

**Comment by BlafKing** [comment]
As long as you're no longer receiving an error in the CMD then it shouldn't be an error with the extension, so to be clear.
You're no longer receiving an error in the CMD?

**Comment by YuckyFox** [comment]
Nope, but it's not downloading anything either without vpn

**Comment by BlafKing** [comment]
Could you let me know if you're still experiencing the issue with the another version I've updated just now with the VPN off?

**Comment by YuckyFox** [comment]
Yep, issue still exists without vpn

**Comment by BlafKing** [comment]
Could you post the error that you get when attempting to download with the latest version?

**Comment by YuckyFox** [comment]
I've not having any errors, download just not starting like on screenshots and yeah, i've got latest updates + no VPN
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/110828409/b0e8f7ad-bf0e-4af3-9762-8db4ca768aff)

**Comment by BlafKing** [comment]
ok thanks for your cooperation so far, I'd like to ask one more thing before I apply the fix from before:
Could you open the civitai_download.py file again and change line 43 from
```
subprocess.Popen(cmd, shell=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
```
to:
```
subprocess.Popen(cmd, shell=True)
```

This will output all logs of the download program (Aria2) to the cmd.

**Comment by YuckyFox** [comment]
Okay, here it is
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/110828409/cfc55754-7d57-4d9b-99ae-8f903702689d)

**Comment by BlafKing** [comment]
Thanks for the error log!
I've just published the fix from before which should allow you to download again.

I unfortunately won't be able to fix the issue where you're unable to download with the VPN turned on.
I'll close this thread for now since your issue should be fixed, thanks for taking the time to reply and try out fixes! :)
If you're still unable to download without the VPN after this update please feel free to send another message

**Comment by YuckyFox** [comment]
U got me wrong, i'm ABLE to download with VPN and UNABLE to download without it still after latest update
Fix not worked for me too :(

**Comment by BlafKing** [comment]
Very odd, I'm not sure what's causing this behaviour.
I'll publish a new update in a bit where you can toggle some options in the Web-UI settings, there you'll be able to turn off downloading using Aria2 (current download method) and then you can use the old download method which should work for you both with and without vpn.

It'll take me a little while to throw this together so expect the update in half an hour or so!
I'll open this issue again and I'll post another message here once I've published the update with these changes 👍🏻

**Comment by YuckyFox** [comment]
Okay, thanks for ur time <3

**Comment by BlafKing** [comment]
I've just published an update which adds a settings tab where you can toggle off downloading with Aria2.
Hopefully this will fix your issue and allow you to download properly again!
Please let me know if you can download again so that I can update this thread status :)

**Comment by YuckyFox** [comment]
With old download method all works fine! But, got a bug not related to this thread
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/110828409/2bf3911e-7efe-4ba4-a804-0857a18e6ba8)
I think this could be fixed with Try/Except if is error is appears

**Comment by BlafKing** [comment]
Thanks for letting me know.
I'll implement a fix for the failed preview image soon :)
and glad to hear downloading is working for you again!
I'll close this thread now since the issue is solved 👍🏻

**Comment by Kirasabi** [comment]
Had same issue, and fixed it by manualy replacing all files inside "stable-diffusion-webui\extensions\sd-civitai-browser-plus\aria2" with "aria2 1.36.0" ([aria2-1.36.0-win-64bit-build1.zip](https://github.com/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0-win-64bit-build1.zip)) from https://github.com/aria2/aria2

**Comment by BlafKing** [comment]
Good to know that fixed the issue for you, the Aria2 shipped with this extension is a custom version of aria2 used in [Motrix](https://github.com/agalwood/Motrix) to allow a larger max connection count than 16 since some users need this to achieve full bandwidth speed.
The version you inserted will only work if your max connections are set to 16 or lower in the settings tab so that's why it's not included by default.

I'll look into compiling my own version of aria2 to help solve this error completely.

**Comment by Kirasabi** [comment]
> Good to know that fixed the issue for you, the Aria2 shipped with this extension is a custom version of aria2 used in [Motrix](https://github.com/agalwood/Motrix) to allow a larger max connection count than 16 since some users need this to achieve full bandwidth speed. The version you inserted will only work if your max connections are set to 16 or lower in the settings tab so that's why it's not included by default.
> 
> I'll look into compiling my own version of aria2 to help solve this error completely.

I think you add reply instantly after i post message. So, nope, that was without aria2, and it's not fixed.
![image](https://github.com/BlafKing/sd-civitai-browser-plus/assets/24381123/e1b59a3e-33a4-42d0-9a84-13eb801829d4)
I think is there might be some dns or ip block request from site, cuz autor of that issue seems from russia (like me) and i had simmilar issue with extention...

**Comment by BlafKing** [comment]
> I think you add reply instantly after i post message that i deleted after settings check. So, nope, that was without aria2, and it's not fixed.

Ah I assumed it was fixed since you posted before that you fixed the issue by replacing Aria2:

> Had same issue, and fixed it by manualy replacing all files inside "stable-diffusion-webui\extensions\sd-civitai-browser-plus\aria2" with "aria2 1.36.0" ([aria2-1.36.0-win-64bit-build1.zip](https://github.com/aria2/aria2/releases/download/release-1.36.0/aria2-1.36.0-win-64bit-build1.zip)) from https://github.com/aria2/aria2

If downloading with Aria2 isn't working at all there isn't much I can do other than letting users with your issue use the other download method which doesn't use Aria2.

You can toggle to use the other downloading method in the Settings under the Civit AI tab which should allow you to download files.

**Comment by Kirasabi** [comment]
> Was downloading still not working when disabling Aria2 for you?

Yep, but i dowloaded this extention for high speed + cool interface so, im trying to investigate trouble. 
I thought it's was a connection limitation, but IDM is able to download with 16 threads without problems.
So, i think, it's might be trouble that site can't recognize aria when downloading, and instantly disabling connection like for ddos protection. Saw some posts that says like "--user-agent=Chrome" might help, but idk where to put it

**Comment by BlafKing** [comment]
You can try to insert that flag inside the civitai_download.py file around line 155 like so

find:
```
    options = {
        "dir": install_path,
        "max-connection-per-server": str(f"{split_aria2}"),
        "split": str(f"{split_aria2}"),
        "async-dns": dns
    }
```

replace with:
```
    options = {
        "dir": install_path,
        "max-connection-per-server": str(f"{split_aria2}"),
        "split": str(f"{split_aria2}"),
        "async-dns": dns,
        "user-agent": "Chrome"
    }
```

You can also try inserting it as a global flag at line 42.

By replacing:
```
cmd = f'"{aria2c}" --enable-rpc --rpc-listen-all --check-certificate=false --ca-certificate=" "'
```
with:
```
cmd = f'"{aria2c}" --enable-rpc --rpc-listen-all --check-certificate=false --ca-certificate=" " --user-agent=Chrome'
```

**Comment by Kirasabi** [comment]
> Also not 100% sure what you mean by "yep" do you mean downloads are working with Aria2 off or still not working with Aria2 off?

Yes, with disabled aria it's working, but with really slow speed.
Tryed add those flags, and seems nothing changed.

With vpn: It's actually downloads (i just stopped it). (screenshot below)
![WindowsTerminal_P1tt52gtdK](https://github.com/BlafKing/sd-civitai-browser-plus/assets/24381123/f50aac07-ee6c-4ee1-acd0-d34633171533)

When i disable vpn and trying to download without restarting web-ui:
![WindowsTerminal_p9CewmEBVm](https://github.com/BlafKing/sd-civitai-browser-plus/assets/24381123/884db29e-c988-42ca-bb2d-2192f507078f)

And without vpn, but restarted web-ui:
![WindowsTerminal_yCN1KJw8ib](https://github.com/BlafKing/sd-civitai-browser-plus/assets/24381123/01a4480d-3007-400f-8f4c-72df060dec14)

Seems there an cloudflare protection, that blocking request from russia (at this time, sadly, some site owners just disabling russian IP's from accessing web-sites).

OR, it's might be an some kind error that i cannot understand (like authentification). When im downloading same model through IDM, it's showing me link that used to be for download, and it's absolutle same (exept date and signature).
![IDMan_86v9gOW3up](https://github.com/BlafKing/sd-civitai-browser-plus/assets/24381123/832aee43-f1ab-4700-b42e-2c1a00378cd4)

Btw, maybe i can download with IDM Because there an "user-agent" params : "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko"

**Comment by Kirasabi** [comment]
Yep, seems it's regional lock\block cuz it's russian segment wide problem i think

**Comment by BlafKing** [comment]
I'm using a VPN to connect from Russia and I'm indeed experiencing the exact same issue, I'll try to troubleshoot to see if there's something that I can find to help the issue 👍🏻
